services:

  my_rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass

#  dundie_awards_front:
#    build: .
#    depends_on:
#      - my_rabbitmq
#    image: dundie_awards:latest
#    restart: always
#    ports:
#      - 3000:3000